chord_id_to_chord_dict = {
1:{'id': '1', 'name': '', 'xml_name': 'major', 'voicing': 'C E G', 'xml_string': b'<chord id="1">\n    <name />\n    <xml>major</xml>\n    <voicing>C E G</voicing>\n    </chord>\n  \n    \n      \n    \n    \n    ', 'degrees': []},
3:{'id': '3', 'name': '5b', 'xml_name': 'major', 'voicing': 'C E Gb', 'xml_string': b'<chord id="3">\n       <name>5b</name>\n       <xml>major</xml>\n       <degree>altb5</degree>\n        <voicing>C E Gb</voicing>\n    </chord>\n  ', 'degrees': ['altb5']},
4:{'id': '4', 'name': '+', 'xml_name': 'augmented', 'voicing': 'C E G#', 'xml_string': b'<chord id="4">\n    <name>+</name>\n    <xml>augmented</xml>\n    <voicing>C E G#</voicing>\n    </chord>\n  ', 'degrees': []},
5:{'id': '5', 'name': '6', 'xml_name': 'major-sixth', 'voicing': 'C E G A', 'xml_string': b'<chord id="5">\n    <name>6</name>\n    <xml>major-sixth</xml>\n    <voicing>C E G A</voicing>\n    </chord>\n  ', 'degrees': []},
6:{'id': '6', 'name': 'Maj7', 'xml_name': 'major-seventh', 'voicing': 'C E G B', 'xml_string': b'<chord id="6">\n    <name>Maj7</name>\n    <xml>major-seventh</xml>\n    <voicing>C E G B</voicing>\n    </chord>\n  ', 'degrees': []},
7:{'id': '7', 'name': 'Maj9', 'xml_name': 'major-ninth', 'voicing': 'C E G B D', 'xml_string': b'<chord id="7">\n    <name>Maj9</name>\n    <xml>major-ninth</xml>\n    <voicing>C E G B D</voicing>\n    </chord>\n  ', 'degrees': []},
8:{'id': '8', 'name': 'Maj9#11', 'xml_name': 'major-ninth', 'voicing': 'C E G B D F#', 'xml_string': b'<chord id="8">\n    <name>Maj9#11</name>\n    <xml>major-ninth</xml>\n    <degree>add#11</degree>\n    <voicing>C E G B D F#</voicing>\n    </chord>\n  ', 'degrees': ['add#11']},
9:{'id': '9', 'name': 'Maj13#11', 'xml_name': 'major-13th', 'voicing': 'C E G B D F# A', 'xml_string': b'<chord id="9">\n    <name>Maj13#11</name>\n    <xml>major-13th</xml>\n    <degree>add#11</degree>\n    <voicing>C E G B D F# A</voicing>\n    </chord>\n  \n    \n    \n    \n    \n  ', 'degrees': ['add#11']},
11:{'id': '11', 'name': 'Maj9(no 3)', 'xml_name': 'major-ninth', 'voicing': 'C G B D', 'xml_string': b'<chord id="11">\n    <name>Maj9(no 3)</name>\n    <xml>major-ninth</xml>\n    <degree>sub3</degree>\n    <voicing>C G B D</voicing>\n    </chord>\n  \n    \n    \n    \n    \n  ', 'degrees': ['sub3']},
13:{'id': '13', 'name': 'Maj7#5', 'xml_name': 'major-seventh', 'voicing': 'C E G# B', 'xml_string': b'<chord id="13">\n    <name>Maj7#5</name>\n    <xml>major-seventh</xml>\n    <degree>alt#5</degree>\n    <voicing>C E G# B</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
14:{'id': '14', 'name': '6add9', 'xml_name': 'major-sixth', 'voicing': 'C E G A D', 'xml_string': b'<chord id="14">\n    <name>6add9</name>\n    <xml>major-sixth</xml>\n    <degree>add9</degree>\n    <voicing>C E G A D</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  ', 'degrees': ['add9']},
16:{'id': '16', 'name': 'm', 'xml_name': 'minor', 'voicing': 'C Eb G', 'xml_string': b'<chord id="16">\n    <name>m</name>\n    <xml>minor</xml>\n    <voicing>C Eb G</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  ', 'degrees': []},
18:{'id': '18', 'name': 'mMaj7', 'xml_name': 'major-minor', 'voicing': 'C Eb G B', 'xml_string': b'<chord id="18">\n    <name>mMaj7</name>\n    <xml>major-minor</xml>\n    <voicing>C Eb G B</voicing>\n    </chord>\n  ', 'degrees': []},
19:{'id': '19', 'name': 'm7', 'xml_name': 'minor-seventh', 'voicing': 'C Eb G Bb', 'xml_string': b'<chord id="19">\n    <name>m7</name>\n    <xml>minor-seventh</xml>\n    <voicing>C Eb G Bb</voicing>\n    </chord>\n  ', 'degrees': []},
20:{'id': '20', 'name': 'm9', 'xml_name': 'minor-ninth', 'voicing': 'C Eb G Bb D', 'xml_string': b'<chord id="20">\n    <name>m9</name>\n    <xml>minor-ninth</xml>\n    <voicing>C Eb G Bb D</voicing>\n    </chord>\n  ', 'degrees': []},
21:{'id': '21', 'name': 'm11', 'xml_name': 'minor-11th', 'voicing': 'C Eb G Bb D F', 'xml_string': b'<chord id="21">\n    <name>m11</name>\n    <xml>minor-11th</xml>\n    <voicing>C Eb G Bb D F</voicing>\n    </chord>\n  ', 'degrees': []},
22:{'id': '22', 'name': 'm13', 'xml_name': 'minor-13th', 'voicing': 'C Eb G Bb D F A', 'xml_string': b'<chord id="22">\n    <name>m13</name>\n    <xml>minor-13th</xml>\n    <voicing>C Eb G Bb D F A</voicing>\n    </chord>\n  ', 'degrees': []},
23:{'id': '23', 'name': 'm6', 'xml_name': 'minor-sixth', 'voicing': 'C Eb G A', 'xml_string': b'<chord id="23">\n    <name>m6</name>\n    <xml>minor-sixth</xml>\n    <voicing>C Eb G A</voicing>\n    </chord>\n  ', 'degrees': []},
24:{'id': '24', 'name': 'm#5', 'xml_name': 'minor', 'voicing': 'C Eb G#', 'xml_string': b'<chord id="24">\n    <name>m#5</name>\n    <xml>minor</xml>\n    <degree>alt#5</degree>\n    <voicing>C Eb G#</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
25:{'id': '25', 'name': 'm7#5', 'xml_name': 'minor-seventh', 'voicing': 'C Eb G# Bb', 'xml_string': b'<chord id="25">\n    <name>m7#5</name>\n    <xml>minor-seventh</xml>\n    <degree>alt#5</degree>\n    <voicing>C Eb G# Bb</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
26:{'id': '26', 'name': 'm6add9', 'xml_name': 'minor-sixth', 'voicing': 'C Eb G A D', 'xml_string': b'<chord id="26">\n    <name>m6add9</name>\n    <xml>minor-sixth</xml>\n    <degree>add9</degree>\n    <voicing>C Eb G A D</voicing>\n    </chord>\n  \n    \n    \n  \n    \n      \n      \n    \n    \n  ', 'degrees': ['add9']},
29:{'id': '29', 'name': 'Maj7b5', 'xml_name': 'major-seventh', 'voicing': 'C E Gb B', 'xml_string': b'<chord id="29">\n    <name>Maj7b5</name>\n    <xml>major-seventh</xml>\n    <degree>altb5</degree>\n    <voicing>C E Gb B</voicing>\n    </chord>\n  ', 'degrees': ['altb5']},
32:{'id': '32', 'name': 'm7b5', 'xml_name': 'half-diminished', 'voicing': 'C Eb Gb Bb', 'xml_string': b'<chord id="32">\n    <name>m7b5</name>\n    <xml>half-diminished</xml>\n    <voicing>C Eb Gb Bb</voicing>\n    </chord>\n  ', 'degrees': []},
33:{'id': '33', 'name': 'dim', 'xml_name': 'diminished', 'voicing': 'C Eb Gb', 'xml_string': b'<chord id="33">\n    <name>dim</name>\n    <xml>diminished</xml>\n    <voicing>C Eb Gb</voicing>\n    </chord>\n  ', 'degrees': []},
34:{'id': '34', 'name': 'm9b5', 'xml_name': 'minor-ninth', 'voicing': 'C Eb Gb Bb D', 'xml_string': b'<chord id="34">\n    <name>m9b5</name>\n    <xml>minor-ninth</xml>\n    <degree>altb5</degree>\n    <voicing>C Eb Gb Bb D</voicing>\n    </chord>\n  ', 'degrees': ['altb5']},
40:{'id': '40', 'name': '5', 'xml_name': 'power', 'voicing': 'C G', 'xml_string': b'<chord id="40">\n    <name>5</name>\n    <xml>power</xml>\n    <voicing>C G</voicing>\n    </chord>\n  ', 'degrees': []},
56:{'id': '56', 'name': '7+', 'xml_name': 'augmented-seventh', 'voicing': 'C E Ab', 'xml_string': b'<chord id="56">\n    <name>7+</name>\n    <xml>augmented-seventh</xml>\n    <voicing>C E Ab</voicing>\n    </chord>\n  ', 'degrees': []},
57:{'id': '57', 'name': '9+', 'xml_name': 'augmented-ninth', 'voicing': 'C E Ab Bb D', 'xml_string': b'<chord id="57">\n    <name>9+</name>\n    <xml>augmented-ninth</xml>\n    <voicing>C E Ab Bb D</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  \n    \n    \n  \n    \n    \n    \n  ', 'degrees': []},
64:{'id': '64', 'name': '7', 'xml_name': 'dominant', 'voicing': 'C E G Bb', 'xml_string': b'<chord id="64">\n    <name>7</name>\n    <xml>dominant</xml>\n    <voicing>C E G Bb</voicing>\n    </chord>\n  ', 'degrees': []},
65:{'id': '65', 'name': '13', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb D F A', 'xml_string': b'<chord id="65">\n    <name>13</name>\n    <xml>dominant-13th</xml>\n    <voicing>C E G Bb D F A</voicing>\n    </chord>\n  ', 'degrees': []},
66:{'id': '66', 'name': '7b13', 'xml_name': 'dominant', 'voicing': 'C E G Ab Bb', 'xml_string': b'<chord id="66">\n    <name>7b13</name>\n    <xml>dominant</xml>\n    <degree>addb13</degree>\n    <voicing>C E G Ab Bb</voicing>\n    </chord>\n  ', 'degrees': ['addb13']},
67:{'id': '67', 'name': '7#11', 'xml_name': 'dominant', 'voicing': 'C E G Bb F#', 'xml_string': b'<chord id="67">\n    <name>7#11</name>\n    <xml>dominant</xml>\n    <degree>add#11</degree>\n    <voicing>C E G Bb F#</voicing>\n    </chord>\n  ', 'degrees': ['add#11']},
68:{'id': '68', 'name': '13#11', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb D F# A', 'xml_string': b'<chord id="68">\n    <name>13#11</name>\n    <xml>dominant-13th</xml>\n    <degree>add#11</degree>\n    <voicing>C E G Bb D F# A</voicing>\n    </chord>\n  ', 'degrees': ['add#11']},
69:{'id': '69', 'name': '7#11b13', 'xml_name': 'dominant', 'voicing': 'C E G Bb F# Ab', 'xml_string': b'<chord id="69">\n    <name>7#11b13</name>\n    <xml>dominant</xml>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C E G Bb F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add#11', 'addb13']},
70:{'id': '70', 'name': '9', 'xml_name': 'dominant-ninth', 'voicing': 'C E G Bb D', 'xml_string': b'<chord id="70">\n    <name>9</name>\n    <xml>dominant-ninth</xml>\n    <voicing>C E G Bb D</voicing>\n    </chord>\n  ', 'degrees': []},
72:{'id': '72', 'name': '9b13', 'xml_name': 'dominant-ninth', 'voicing': 'C E G Bb D Ab', 'xml_string': b'<chord id="72">\n    <name>9b13</name>\n    <xml>dominant-ninth</xml>\n    <degree>addb13</degree>\n    <voicing>C E G Bb D Ab</voicing>\n    </chord>\n  ', 'degrees': ['addb13']},
73:{'id': '73', 'name': '9#11', 'xml_name': 'dominant-ninth', 'voicing': 'C E G Bb D F#', 'xml_string': b'<chord id="73">\n    <name>9#11</name>\n    <xml>dominant-ninth</xml>\n    <degree>add#11</degree>\n    <voicing>C E G Bb D F#</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  ', 'degrees': ['add#11']},
75:{'id': '75', 'name': '9#11b13', 'xml_name': 'dominant-ninth', 'voicing': 'C E G Bb D F# Ab', 'xml_string': b'<chord id="75">\n    <name>9#11b13</name>\n    <xml>dominant-ninth</xml>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C E G Bb D F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add#11', 'addb13']},
76:{'id': '76', 'name': '7b9', 'xml_name': 'dominant', 'voicing': 'C E G Bb Db', 'xml_string': b'<chord id="76">\n    <name>7b9</name>\n    <xml>dominant</xml>\n    <degree>addb9</degree>\n    <voicing>C E G Bb Db</voicing>\n    </chord>\n  ', 'degrees': ['addb9']},
77:{'id': '77', 'name': '13b9', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb Db F A', 'xml_string': b'<chord id="77">\n    <name>13b9</name>\n    <xml>dominant-13th</xml>\n    <degree>altb9</degree>\n    <voicing>C E G Bb Db F A</voicing>\n    </chord>\n  ', 'degrees': ['altb9']},
78:{'id': '78', 'name': '7b9b13', 'xml_name': 'dominant', 'voicing': 'C E G Bb Db Ab', 'xml_string': b'<chord id="78">\n    <name>7b9b13</name>\n    <xml>dominant</xml>\n    <degree>addb9</degree>\n    <degree>addb13</degree>\n    <voicing>C E G Bb Db Ab</voicing>\n    </chord>\n  ', 'degrees': ['addb9', 'addb13']},
79:{'id': '79', 'name': '7b9#11', 'xml_name': 'dominant', 'voicing': 'C E G Bb Db F#', 'xml_string': b'<chord id="79">\n    <name>7b9#11</name>\n    <xml>dominant</xml>\n    <degree>addb9</degree>\n    <degree>alt#11</degree>\n    <voicing>C E G Bb Db F#</voicing>\n    </chord>\n  ', 'degrees': ['addb9', 'alt#11']},
80:{'id': '80', 'name': '13b9#11', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb Db F# A', 'xml_string': b'<chord id="80">\n    <name>13b9#11</name>\n    <xml>dominant-13th</xml>\n    <degree>altb9</degree>\n    <degree>alt#11</degree>\n    <voicing>C E G Bb Db F# A</voicing>\n    </chord>\n  ', 'degrees': ['altb9', 'alt#11']},
81:{'id': '81', 'name': '7b9#11b13', 'xml_name': 'dominant', 'voicing': 'C E G Bb Db F# Ab', 'xml_string': b'<chord id="81">\n    <name>7b9#11b13</name>\n    <xml>dominant</xml>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C E G Bb Db F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add#11', 'addb13']},
82:{'id': '82', 'name': '7#9', 'xml_name': 'dominant', 'voicing': 'C E G Bb Eb', 'xml_string': b'<chord id="82">\n    <name>7#9</name>\n    <xml>dominant</xml>\n    <degree>add#9</degree>\n    <voicing>C E G Bb Eb</voicing>\n    </chord>\n  ', 'degrees': ['add#9']},
83:{'id': '83', 'name': '13#9', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb D# F A', 'xml_string': b'<chord id="83">\n    <name>13#9</name>\n    <xml>dominant-13th</xml>\n    <degree>alt#9</degree>\n    <voicing>C E G Bb D# F A</voicing>\n    </chord>\n  ', 'degrees': ['alt#9']},
84:{'id': '84', 'name': '7#9b13', 'xml_name': 'dominant', 'voicing': 'C E G Bb D# Ab', 'xml_string': b'<chord id="84">\n    <name>7#9b13</name>\n    <xml>dominant</xml>\n    <degree>add#9</degree>\n    <degree>addb13</degree>\n    <voicing>C E G Bb D# Ab</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  ', 'degrees': ['add#9', 'addb13']},
86:{'id': '86', 'name': '13#9#11', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb D# F# A', 'xml_string': b'<chord id="86">\n    <name>13#9#11</name>\n    <xml>dominant-13th</xml>\n    <degree>alt#9</degree>\n    <degree>alt#11</degree>\n    <voicing>C E G Bb D# F# A</voicing>\n    </chord>\n  ', 'degrees': ['alt#9', 'alt#11']},
87:{'id': '87', 'name': '7#9#11b13', 'xml_name': 'dominant', 'voicing': 'C E G Bb D# F# Ab', 'xml_string': b'<chord id="87">\n    <name>7#9#11b13</name>\n    <xml>dominant</xml>\n    <degree>add#9</degree>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C E G Bb D# F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add#9', 'add#11', 'addb13']},
88:{'id': '88', 'name': '7b5', 'xml_name': 'dominant', 'voicing': 'C E Gb Bb', 'xml_string': b'<chord id="88">\n    <name>7b5</name>\n    <xml>dominant</xml>\n    <degree>altb5</degree>\n    <voicing>C E Gb Bb</voicing>\n    </chord>\n  ', 'degrees': ['altb5']},
89:{'id': '89', 'name': '13b5', 'xml_name': 'dominant-13th', 'voicing': 'C E Gb Bb D F A', 'xml_string': b'<chord id="89">\n    <name>13b5</name>\n    <xml>dominant-13th</xml>\n    <degree>altb5</degree>\n    <voicing>C E Gb Bb D F A</voicing>\n    </chord>\n  ', 'degrees': ['altb5']},
90:{'id': '90', 'name': '7b5b13', 'xml_name': 'dominant', 'voicing': 'C E Gb Bb A', 'xml_string': b'<chord id="90">\n    <name>7b5b13</name>\n    <xml>dominant</xml>\n    <degree>altb5</degree>\n    <degree>addb13</degree>\n    <voicing>C E Gb Bb A</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'addb13']},
91:{'id': '91', 'name': '9b5', 'xml_name': 'dominant-ninth', 'voicing': 'C E Gb Bb D', 'xml_string': b'<chord id="91">\n    <name>9b5</name>\n    <xml>dominant-ninth</xml>\n    <degree>altb5</degree>\n    <voicing>C E Gb Bb D</voicing>\n    </chord>\n  ', 'degrees': ['altb5']},
92:{'id': '92', 'name': '9b5b13', 'xml_name': 'dominant-ninth', 'voicing': 'C E Gb Bb D Ab', 'xml_string': b'<chord id="92">\n    <name>9b5b13</name>\n    <xml>dominant-ninth</xml>\n    <degree>altb5</degree>\n    <degree>addb13</degree>\n    <voicing>C E Gb Bb D Ab</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'addb13']},
93:{'id': '93', 'name': '7b5b9', 'xml_name': 'dominant', 'voicing': 'C E Gb Bb Db', 'xml_string': b'<chord id="93">\n    <name>7b5b9</name>\n    <xml>dominant</xml>\n    <degree>altb5</degree>\n    <degree>addb9</degree>\n    <voicing>C E Gb Bb Db</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'addb9']},
94:{'id': '94', 'name': '13b5b9', 'xml_name': 'dominant-13th', 'voicing': 'C E Gb Bb Db F A', 'xml_string': b'<chord id="94">\n    <name>13b5b9</name>\n    <xml>dominant-13th</xml>\n    <degree>altb5</degree>\n    <degree>addb9</degree>\n    <voicing>C E Gb Bb Db F A</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'addb9']},
95:{'id': '95', 'name': '7b5b9b13', 'xml_name': 'dominant', 'voicing': 'C E Gb Bb Db Ab', 'xml_string': b'<chord id="95">\n    <name>7b5b9b13</name>\n    <xml>dominant</xml>\n    <degree>altb5</degree>\n    <degree>addb9</degree>\n    <degree>addb13</degree>\n    <voicing>C E Gb Bb Db Ab</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'addb9', 'addb13']},
96:{'id': '96', 'name': '7b5#9', 'xml_name': 'dominant', 'voicing': 'C E Gb Bb D#', 'xml_string': b'<chord id="96">\n    <name>7b5#9</name>\n    <xml>dominant</xml>\n    <degree>altb5</degree>\n    <degree>add#9</degree>\n    <voicing>C E Gb Bb D#</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'add#9']},
97:{'id': '97', 'name': '13b5#9', 'xml_name': 'dominant-13th', 'voicing': 'C E Gb Bb D# F A', 'xml_string': b'<chord id="97">\n    <name>13b5#9</name>\n    <xml>dominant-13th</xml>\n    <degree>altb5</degree>\n    <degree>alt#9</degree>\n    <voicing>C E Gb Bb D# F A</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'alt#9']},
98:{'id': '98', 'name': '7b5#9b13', 'xml_name': 'dominant', 'voicing': 'C E Gb Bb D# Ab', 'xml_string': b'<chord id="98">\n    <name>7b5#9b13</name>\n    <xml>dominant</xml>\n    <degree>altb5</degree>\n    <degree>add#9</degree>\n    <degree>addb13</degree>\n    <voicing>C E Gb Bb D# Ab</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'add#9', 'addb13']},
99:{'id': '99', 'name': '7#5', 'xml_name': 'augmented-seventh', 'voicing': 'C E Ab Bb', 'xml_string': b'<chord id="99">\n    <name>7#5</name>\n    <xml>augmented-seventh</xml>\n    <voicing>C E Ab Bb</voicing>\n    </chord>\n  ', 'degrees': []},
100:{'id': '100', 'name': '13#5', 'xml_name': 'dominant-13th', 'voicing': 'C E G# Bb D F A', 'xml_string': b'<chord id="100">\n    <name>13#5</name>\n    <xml>dominant-13th</xml>\n    <degree>alt#5</degree>\n    <voicing>C E G# Bb D F A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
101:{'id': '101', 'name': '7#5#11', 'xml_name': 'dominant', 'voicing': 'C E G# Bb F#', 'xml_string': b'<chord id="101">\n    <name>7#5#11</name>\n    <xml>dominant</xml>\n    <degree>alt#5</degree>\n    <degree>add#11</degree>\n    <voicing>C E G# Bb F#</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n    \n  ', 'degrees': ['alt#5', 'add#11']},
103:{'id': '103', 'name': '9#5', 'xml_name': 'dominant-ninth', 'voicing': 'C E G# Bb D', 'xml_string': b'<chord id="103">\n    <name>9#5</name>\n    <xml>dominant-ninth</xml>\n    <degree>alt#5</degree>\n    <voicing>C E G# Bb D</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
104:{'id': '104', 'name': '9#5#11', 'xml_name': 'dominant-ninth', 'voicing': 'C E G# Bb D F#', 'xml_string': b'<chord id="104">\n    <name>9#5#11</name>\n    <xml>dominant-ninth</xml>\n    <degree>alt#5</degree>\n    <degree>add#11</degree>\n    <voicing>C E G# Bb D F#</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add#11']},
105:{'id': '105', 'name': '7#5b9', 'xml_name': 'dominant', 'voicing': 'C E G# Bb Db', 'xml_string': b'<chord id="105">\n    <name>7#5b9</name>\n    <xml>dominant</xml>\n    <degree>alt#5</degree>\n    <degree>addb9</degree>\n    <voicing>C E G# Bb Db</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'addb9']},
106:{'id': '106', 'name': '13#5b9', 'xml_name': 'dominant-13th', 'voicing': 'C E G# Bb Db F A', 'xml_string': b'<chord id="106">\n    <name>13#5b9</name>\n    <xml>dominant-13th</xml>\n    <degree>alt#5</degree>\n    <degree>altb9</degree>\n    <voicing>C E G# Bb Db F A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'altb9']},
107:{'id': '107', 'name': '7#5b9#11', 'xml_name': 'dominant', 'voicing': 'C E G# Bb Db F#', 'xml_string': b'<chord id="107">\n    <name>7#5b9#11</name>\n    <xml>dominant</xml>\n    <degree>alt#5</degree>\n    <degree>addb9</degree>\n    <degree>add#11</degree>\n    <voicing>C E G# Bb Db F#</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'addb9', 'add#11']},
108:{'id': '108', 'name': '13#5b9#11', 'xml_name': 'dominant-13th', 'voicing': 'C E G# Bb Db F# A', 'xml_string': b'<chord id="108">\n    <name>13#5b9#11</name>\n    <xml>dominant-13th</xml>\n    <degree>alt#5</degree>\n    <degree>altb9</degree>\n    <degree>alt#11</degree>\n    <voicing>C E G# Bb Db F# A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'altb9', 'alt#11']},
109:{'id': '109', 'name': '7#5#9', 'xml_name': 'dominant', 'voicing': 'C E G# Bb D#', 'xml_string': b'<chord id="109">\n    <name>7#5#9</name>\n    <xml>dominant</xml>\n    <degree>alt#5</degree>\n    <degree>add#9</degree>\n    <voicing>C E G# Bb D#</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add#9']},
110:{'id': '110', 'name': '13#5#9#11', 'xml_name': 'dominant-13th', 'voicing': 'C E G# Bb D# F# A', 'xml_string': b'<chord id="110">\n    <name>13#5#9#11</name>\n    <xml>dominant-13th</xml>\n    <degree>alt#5</degree>\n    <degree>alt#9</degree>\n    <degree>alt#11</degree>\n    <voicing>C E G# Bb D# F# A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'alt#9', 'alt#11']},
111:{'id': '111', 'name': '7#5#9#11', 'xml_name': 'dominant', 'voicing': 'C E G# Bb D# F#', 'xml_string': b'<chord id="111">\n    <name>7#5#9#11</name>\n    <xml>dominant</xml>\n    <degree>alt#5</degree>\n    <degree>add#9</degree>\n    <degree>add#11</degree>\n    <voicing>C E G# Bb D# F#</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n    \n    \n  ', 'degrees': ['alt#5', 'add#9', 'add#11']},
113:{'id': '113', 'name': '7#5', 'xml_name': 'dominant', 'voicing': 'C E G# Bb', 'xml_string': b'<chord id="113">\n    <name>7#5</name>\n    <xml>dominant</xml>\n    <degree>alt#5</degree>\n    <voicing>C E G# Bb</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
128:{'id': '128', 'name': '7sus', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb', 'xml_string': b'<chord id="128">\n    <name>7sus</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <voicing>C F G Bb</voicing>\n    </chord>\n  ', 'degrees': ['add7']},
129:{'id': '129', 'name': '13sus', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D A', 'xml_string': b'<chord id="129">\n    <name>13sus</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add13</degree>\n    <voicing>C F G Bb D A</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add13']},
130:{'id': '130', 'name': '7susb13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Ab', 'xml_string': b'<chord id="130">\n    <name>7susb13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'addb13']},
131:{'id': '131', 'name': '7sus#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb F', 'xml_string': b'<chord id="131">\n    <name>7sus#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#11</degree>\n    <voicing>C F G Bb F</voicing>\n    </chord>\n  \n    \n    \n      \n      \n    \n    \n    \n    \n  ', 'degrees': ['add7', 'add#11']},
133:{'id': '133', 'name': '7sus#11b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb F# Ab', 'xml_string': b'<chord id="133">\n    <name>7sus#11b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add#11', 'addb13']},
134:{'id': '134', 'name': '9sus', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D', 'xml_string': b'<chord id="134">\n    <name>9sus</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <voicing>C F G Bb D</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add9']},
135:{'id': '135', 'name': '9susb13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D Ab', 'xml_string': b'<chord id="135">\n    <name>9susb13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb D Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add9', 'addb13']},
136:{'id': '136', 'name': '9sus#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D F#', 'xml_string': b'<chord id="136">\n    <name>9sus#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add#11</degree>\n    <voicing>C F G Bb D F#</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add9', 'add#11']},
137:{'id': '137', 'name': '13sus#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D F# A', 'xml_string': b'<chord id="137">\n    <name>13sus#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add#11</degree>\n    <degree>add13</degree>\n    <voicing>C F G Bb D F# A</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n    \n    \n    \n  ', 'degrees': ['add7', 'add9', 'add#11', 'add13']},
139:{'id': '139', 'name': '9sus#11b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D F# Ab', 'xml_string': b'<chord id="139">\n    <name>9sus#11b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb D F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add9', 'add#11', 'addb13']},
140:{'id': '140', 'name': '7susb9', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Db', 'xml_string': b'<chord id="140">\n    <name>7susb9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>addb9</degree>\n    <voicing>C F G Bb Db</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'addb9']},
141:{'id': '141', 'name': '13susb9', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Db F A', 'xml_string': b'<chord id="141">\n    <name>13susb9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>addb9</degree>\n    <degree>add11</degree>\n    <degree>add13</degree>\n    <voicing>C F G Bb Db F A</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'addb9', 'add11', 'add13']},
142:{'id': '142', 'name': '7susb9b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Db Ab', 'xml_string': b'<chord id="142">\n    <name>7susb9b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>addb9</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb Db Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'addb9', 'addb13']},
143:{'id': '143', 'name': '7susb9#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Db F#', 'xml_string': b'<chord id="143">\n    <name>7susb9#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>addb9</degree>\n    <degree>add#11</degree>\n    <voicing>C F G Bb Db F#</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'addb9', 'add#11']},
144:{'id': '144', 'name': '13susb9#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Dd F# A', 'xml_string': b'<chord id="144">\n    <name>13susb9#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>addb9</degree>\n    <degree>add#11</degree>\n    <degree>add13</degree>\n    <voicing>C F G Bb Dd F# A</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'addb9', 'add#11', 'add13']},
145:{'id': '145', 'name': '7susb9#11b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Db F# Ab', 'xml_string': b'<chord id="145">\n    <name>7susb9#11b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>addb9</degree>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb Db F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'addb9', 'add#11', 'addb13']},
146:{'id': '146', 'name': '7sus#9', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb Eb', 'xml_string': b'<chord id="146">\n    <name>7sus#9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <voicing>C F G Bb Eb</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add#9']},
147:{'id': '147', 'name': '13sus#9', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D# A', 'xml_string': b'<chord id="147">\n    <name>13sus#9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <degree>add13</degree>\n    <voicing>C F G Bb D# A</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add#9', 'add13']},
148:{'id': '148', 'name': '7sus#9b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D# Ab', 'xml_string': b'<chord id="148">\n    <name>7sus#9b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb D# Ab</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n    \n    \n  ', 'degrees': ['add7', 'add#9', 'addb13']},
150:{'id': '150', 'name': '13sus#9#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D# F# A', 'xml_string': b'<chord id="150">\n    <name>13sus#9#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <degree>add#11</degree>\n    <degree>add13</degree>\n    <voicing>C F G Bb D# F# A</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add#9', 'add#11', 'add13']},
151:{'id': '151', 'name': '7sus#9#11b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D# F# Ab', 'xml_string': b'<chord id="151">\n    <name>7sus#9#11b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <degree>add#11</degree>\n    <degree>addb13</degree>\n    <voicing>C F G Bb D# F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add#9', 'add#11', 'addb13']},
152:{'id': '152', 'name': '7susb5', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb', 'xml_string': b'<chord id="152">\n    <name>7susb5</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>altb5</degree>\n    <voicing>C F Gb Bb</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'altb5']},
153:{'id': '153', 'name': '13susb5', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb D A', 'xml_string': b'<chord id="153">\n    <name>13susb5</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add13</degree>\n    <voicing>C F Gb Bb D A</voicing>\n    </chord>\n  ', 'degrees': ['alt5', 'add7', 'add9', 'add13']},
154:{'id': '154', 'name': '7susb5b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb Ab', 'xml_string': b'<chord id="154">\n    <name>7susb5b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>altb5</degree>\n    <degree>addb13</degree>\n    <voicing>C F Gb Bb Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'altb5', 'addb13']},
155:{'id': '155', 'name': '9susb5', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb D', 'xml_string': b'<chord id="155">\n    <name>9susb5</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <voicing>C F Gb Bb D</voicing>\n    </chord>\n  ', 'degrees': ['alt5', 'add7', 'add9']},
156:{'id': '156', 'name': '9susb5b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb D Ab', 'xml_string': b'<chord id="156">\n    <name>9susb5b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add13</degree>\n    <voicing>C F Gb Bb D Ab</voicing>\n    </chord>\n  ', 'degrees': ['alt5', 'add7', 'add9', 'add13']},
157:{'id': '157', 'name': '7susb5b9', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb Db', 'xml_string': b'<chord id="157">\n    <name>7susb5b9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>altb5</degree>\n    <degree>addb9</degree>\n    <voicing>C F Gb Bb Db</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n    \n    \n    \n  ', 'degrees': ['add7', 'altb5', 'addb9']},
159:{'id': '159', 'name': '7susb5b9b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb Db Ab', 'xml_string': b'<chord id="159">\n    <name>7susb5b9b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>altb5</degree>\n    <degree>addb9</degree>\n    <degree>addb13</degree>\n    <voicing>C F Gb Bb Db Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'altb5', 'addb9', 'addb13']},
160:{'id': '160', 'name': '7susb5#9', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb Eb', 'xml_string': b'<chord id="160">\n    <name>7susb5#9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>altb5</degree>\n    <degree>add#9</degree>\n    <voicing>C F Gb Bb Eb</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'altb5', 'add#9']},
161:{'id': '161', 'name': '13susb5#9', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb D# A', 'xml_string': b'<chord id="161">\n    <name>13susb5#9</name>\n    <xml>suspended-fourth</xml>\n    <degree>altb5</degree>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <degree>add13</degree>\n    <voicing>C F Gb Bb D# A</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'add7', 'add#9', 'add13']},
162:{'id': '162', 'name': '7susb5#9b13', 'xml_name': 'suspended-fourth', 'voicing': 'C F Gb Bb Eb Ab', 'xml_string': b'<chord id="162">\n    <name>7susb5#9b13</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>altb5</degree>\n    <degree>add#9</degree>\n    <degree>addb13</degree>\n    <voicing>C F Gb Bb Eb Ab</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'altb5', 'add#9', 'addb13']},
163:{'id': '163', 'name': '7sus#5', 'xml_name': 'suspended-fourth', 'voicing': 'C F Ab Bb', 'xml_string': b'<chord id="163">\n    <name>7sus#5</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>alt#5</degree>\n    <voicing>C F Ab Bb</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'alt#5']},
164:{'id': '164', 'name': '13sus#5', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb D A', 'xml_string': b'<chord id="164">\n    <name>13sus#5</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt#5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add13</degree>\n    <voicing>C F G# Bb D A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add7', 'add9', 'add13']},
165:{'id': '165', 'name': '7sus#5#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb F#', 'xml_string': b'<chord id="165">\n    <name>7sus#5#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>alt#5</degree>\n    <degree>add#11</degree>\n    <voicing>C F G# Bb F#</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'alt#5', 'add#11']},
166:{'id': '166', 'name': '13sus#5#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb D F# A', 'xml_string': b'<chord id="166">\n    <name>13sus#5#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt#5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add#11</degree>\n    <degree>add13</degree>\n    <voicing>C F G# Bb D F# A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add7', 'add9', 'add#11', 'add13']},
167:{'id': '167', 'name': '9sus#5', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb D', 'xml_string': b'<chord id="167">\n    <name>9sus#5</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt#5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <voicing>C F G# Bb D</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add7', 'add9']},
168:{'id': '168', 'name': '9sus#5#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb D F#', 'xml_string': b'<chord id="168">\n    <name>9sus#5#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt#5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add#11</degree>\n    <voicing>C F G# Bb D F#</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add7', 'add9', 'add#11']},
169:{'id': '169', 'name': '7sus#5b9', 'xml_name': 'suspended-fourth', 'voicing': 'C F Ab Bb Db', 'xml_string': b'<chord id="169">\n    <name>7sus#5b9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>alt#5</degree>\n    <degree>addb9</degree>\n    <voicing>C F Ab Bb Db</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'alt#5', 'addb9']},
170:{'id': '170', 'name': '13sus#5b9', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb Db A', 'xml_string': b'<chord id="170">\n    <name>13sus#5b9</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt#5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add13</degree>\n    <voicing>C F G# Bb Db A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add7', 'add9', 'add13']},
171:{'id': '171', 'name': '7sus#5b9#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F Ab Bb Db Gb', 'xml_string': b'<chord id="171">\n    <name>7sus#5b9#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>alt#5</degree>\n    <degree>addb9</degree>\n    <degree>add#11</degree>\n    <voicing>C F Ab Bb Db Gb</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'alt#5', 'addb9', 'add#11']},
172:{'id': '172', 'name': '13sus#5b9#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb Db F# A', 'xml_string': b'<chord id="172">\n    <name>13sus#5b9#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt#5</degree>\n    <degree>add7</degree>\n    <degree>add9</degree>\n    <degree>add#11</degree>\n    <degree>add13</degree>\n    <voicing>C F G# Bb Db F# A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add7', 'add9', 'add#11', 'add13']},
173:{'id': '173', 'name': '7sus#5#9', 'xml_name': 'suspended-fourth', 'voicing': 'C F Ab Bb Eb', 'xml_string': b'<chord id="173">\n    <name>7sus#5#9</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>alt#5</degree>\n    <degree>add#9</degree>\n    <voicing>C F Ab Bb Eb</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'alt#5', 'add#9']},
174:{'id': '174', 'name': '13sus#5#9#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F G# Bb D# F# A', 'xml_string': b'<chord id="174">\n    <name>13sus#5#9#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>alt#5</degree>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <degree>add#11</degree>\n    <degree>add13</degree>\n    <voicing>C F G# Bb D# F# A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5', 'add7', 'add#9', 'add#11', 'add13']},
175:{'id': '175', 'name': '7sus#5#9#11', 'xml_name': 'suspended-fourth', 'voicing': 'C F Ab Bb Eb Gb', 'xml_string': b'<chord id="175">\n    <name>7sus#5#9#11</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>alt#5</degree>\n    <degree>add#9</degree>\n    <degree>add#11</degree>\n    <voicing>C F Ab Bb Eb Gb</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  ', 'degrees': ['add7', 'alt#5', 'add#9', 'add#11']},
177:{'id': '177', 'name': 'add4', 'xml_name': 'major', 'voicing': 'C E F G', 'xml_string': b'<chord id="177">\n    <name>add4</name>\n    <xml>major</xml>\n    <degree>add4</degree>\n    <voicing>C E F G</voicing>\n    </chord>\n  ', 'degrees': ['add4']},
184:{'id': '184', 'name': 'sus', 'xml_name': 'suspended-fourth', 'voicing': 'C F G', 'xml_string': b'<chord id="184">\n    <name>sus</name>\n    <xml>suspended-fourth</xml>\n    <voicing>C F G</voicing>\n    </chord>\n  ', 'degrees': []},
185:{'id': '185', 'name': 'dim7', 'xml_name': 'diminished-seventh', 'voicing': 'C Eb Gb Bbb', 'xml_string': b'<chord id="185">\n    <name>dim7</name>\n    <xml>diminished-seventh</xml>\n    <voicing>C Eb Gb Bbb</voicing>\n    </chord>\n  ', 'degrees': []},
186:{'id': '186', 'name': 'sus2', 'xml_name': 'suspended-second', 'voicing': 'C D G', 'xml_string': b'<chord id="186">\n    <name>sus2</name>\n    <xml>suspended-second</xml>\n    <voicing>C D G</voicing>\n    </chord>\n  ', 'degrees': []},
187:{'id': '187', 'name': 'maddb13', 'xml_name': 'minor', 'voicing': 'C Eb Ab', 'xml_string': b'<chord id="187">\n    <name>maddb13</name>\n    <xml>minor</xml>\n    <degree>addb13</degree>\n    <voicing>C Eb Ab</voicing>\n    </chord>\n  ', 'degrees': ['addb13']},
188:{'id': '188', 'name': 'add#13', 'xml_name': 'major', 'voicing': 'C E G A#', 'xml_string': b'<chord id="188">\n    <name>add#13</name>\n    <xml>major</xml>\n    <degree>add#13</degree>\n    <voicing>C E G A#</voicing>\n    </chord>\n  ', 'degrees': ['add#13']},
189:{'id': '189', 'name': 'add#11#13', 'xml_name': 'major', 'voicing': 'C E G F# A#', 'xml_string': b'<chord id="189">\n    <name>add#11#13</name>\n    <xml>major</xml>\n    <degree>add#11</degree>\n    <degree>add#13</degree>\n    <voicing>C E G F# A#</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  ', 'degrees': ['add#11', 'add#13']},
191:{'id': '191', 'name': '6add9', 'xml_name': 'major-sixth', 'voicing': 'C E G A D', 'xml_string': b'<chord id="191">\n    <name>6add9</name>\n    <xml>major-sixth</xml>\n    <degree>add9</degree>\n    <voicing>C E G A D</voicing>\n    </chord>\n  \n    \n    \n    \n    \n  ', 'degrees': ['add9']},
193:{'id': '193', 'name': '11', 'xml_name': 'dominant-11th', 'voicing': 'C E G Bb D F', 'xml_string': b'<chord id="193">\n    <name>11</name>\n    <xml>dominant-11th</xml>\n    <voicing>C E G Bb D F</voicing>\n    </chord>\n  ', 'degrees': []},
194:{'id': '194', 'name': 'Maj11', 'xml_name': 'major-11th', 'voicing': 'C E G B D F', 'xml_string': b'<chord id="194">\n    <name>Maj11</name>\n    <xml>major-11th</xml>\n    <voicing>C E G B D F</voicing>\n    </chord>\n  ', 'degrees': []},
195:{'id': '195', 'name': 'Tristan', 'xml_name': 'Tristan', 'voicing': 'C F# A# D', 'xml_string': b'<chord id="195">\n    <name>Tristan</name>\n    <xml>Tristan</xml>\n    <voicing>C F# A# D</voicing>\n    </chord>\n  ', 'degrees': []},
196:{'id': '196', 'name': 'm7add11', 'xml_name': 'minor-seventh', 'voicing': 'C Eb F G Bb', 'xml_string': b'<chord id="196">\n    <name>m7add11</name>\n    <xml>minor-seventh</xml>\n    <degree>add11</degree>\n    <voicing>C Eb F G Bb</voicing>\n    </chord>\n  ', 'degrees': ['add11']},
197:{'id': '197', 'name': 'Maj7add13', 'xml_name': 'major-seventh', 'voicing': 'C E G A B', 'xml_string': b'<chord id="197">\n    <name>Maj7add13</name>\n    <xml>major-seventh</xml>\n    <degree>add13</degree>\n    <voicing>C E G A B</voicing>\n    </chord>\n  ', 'degrees': ['add13']},
198:{'id': '198', 'name': 'madd9', 'xml_name': 'minor', 'voicing': 'C D Eb G', 'xml_string': b'<chord id="198">\n    <name>madd9</name>\n    <xml>minor</xml>\n    <degree>add9</degree>\n    <voicing>C D Eb G</voicing>\n    </chord>\n  ', 'degrees': ['add9']},
199:{'id': '199', 'name': 'm9Maj7', 'xml_name': 'major-minor', 'voicing': 'C Eb G B D', 'xml_string': b'<chord id="199">\n    <name>m9Maj7</name>\n    <xml>major-minor</xml>\n    <degree>add9</degree>\n    <voicing>C Eb G B D</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  ', 'degrees': ['add9']},
201:{'id': '201', 'name': 'm11b5', 'xml_name': 'minor-11th', 'voicing': 'C Eb Gb Bb D F', 'xml_string': b'<chord id="201">\n    <name>m11b5</name>\n    <xml>minor-11th</xml>\n    <degree>altb5</degree>\n    <voicing>C Eb Gb Bb D F</voicing>\n    </chord>\n  ', 'degrees': ['altb5']},
202:{'id': '202', 'name': 'dimMaj7', 'xml_name': 'diminished', 'voicing': 'C Eb Gb B', 'xml_string': b'<chord id="202">\n    <name>dimMaj7</name>\n    <xml>diminished</xml>\n    <degree>add#7</degree>\n      <voicing>C Eb Gb B</voicing>\n    </chord>\n  ', 'degrees': ['add#7']},
203:{'id': '203', 'name': 'aug9', 'xml_name': 'augmented-seventh', 'voicing': 'C E Ab D', 'xml_string': b'<chord id="203">\n    <name>aug9</name>\n    <xml>augmented-seventh</xml>\n    <degree>add9</degree>\n    <voicing>C E Ab D</voicing>\n    </chord>\n  ', 'degrees': ['add9']},
204:{'id': '204', 'name': 'omit5', 'xml_name': 'major', 'voicing': 'C E', 'xml_string': b'<chord id="204">\n    <name>omit5</name>\n    <xml>major</xml>\n    <degree>sub5</degree>\n    <voicing>C E</voicing>\n    </chord>\n  \n    \n    \n    \n    \n  \n    \n    \n    \n    \n  ', 'degrees': ['sub5']},
207:{'id': '207', 'name': 'aug13', 'xml_name': 'dominant-13th', 'voicing': 'C E G# Bb D A', 'xml_string': b'<chord id="207">\n    <name>aug13</name>\n    <xml>dominant-13th</xml>\n    <degree>alt#5</degree>\n    <voicing>C E G# Bb D A</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
210:{'id': '210', 'name': 'Maj7#11', 'xml_name': 'major-seventh', 'voicing': 'C E G B F#', 'xml_string': b'<chord id="210">\n    <name>Maj7#11</name>\n    <xml>major-seventh</xml>\n    <degree>add#11</degree>\n    <voicing>C E G B F#</voicing>\n    </chord>\n  ', 'degrees': ['add#11']},
211:{'id': '211', 'name': 'Maj9#5', 'xml_name': 'major-ninth', 'voicing': 'C E G# B D', 'xml_string': b'<chord id="211">\n    <name>Maj9#5</name>\n    <xml>major-ninth</xml>\n    <degree>alt#5</degree>\n    <voicing>C E G# B D</voicing>\n    </chord>\n  ', 'degrees': ['alt#5']},
212:{'id': '212', 'name': 'Maj7#9', 'xml_name': 'major-seventh', 'voicing': 'C E G B D#', 'xml_string': b'<chord id="212">\n    <name>Maj7#9</name>\n    <xml>major-seventh</xml>\n    <degree>add#9</degree>\n    <voicing>C E G B D#</voicing>\n    </chord>\n  ', 'degrees': ['add#9']},
213:{'id': '213', 'name': 'add2', 'xml_name': 'major', 'voicing': 'C D E G', 'xml_string': b'<chord id="213">\n    <name>add2</name>\n    <xml>major</xml>\n    <degree>add2</degree>\n    <voicing>C D E G</voicing>\n    </chord>\n  ', 'degrees': ['add2']},
214:{'id': '214', 'name': 'add9', 'xml_name': 'major', 'voicing': 'C E G D', 'xml_string': b'<chord id="214">\n    <name>add9</name>\n    <xml>major</xml>\n    <degree>add9</degree>\n    <voicing>C E G D</voicing>\n    </chord>\n  ', 'degrees': ['add9']},
215:{'id': '215', 'name': 'susb9', 'xml_name': 'suspended-fourth', 'voicing': 'C Db F G', 'xml_string': b'<chord id="215">\n    <name>susb9</name>\n    <xml>suspended-fourth</xml>\n    <degree>addb9</degree>\n    <voicing>C Db F G</voicing>\n    </chord>\n  ', 'degrees': ['addb9']},
216:{'id': '216', 'name': 'Maj7sus', 'xml_name': 'major-seventh', 'voicing': 'C F G B', 'xml_string': b'<chord id="216">\n    <name>Maj7sus</name>\n    <xml>major-seventh</xml>\n    <degree>sub3</degree>\n    <degree>add4</degree>\n    <voicing>C F G B</voicing>\n    </chord>\n  ', 'degrees': ['sub3', 'add4']},
217:{'id': '217', 'name': 'Maj9sus', 'xml_name': 'major-ninth', 'voicing': 'C F G B D', 'xml_string': b'<chord id="217">\n    <name>Maj9sus</name>\n    <xml>major-ninth</xml>\n    <degree>sub3</degree>\n    <degree>add4</degree>\n    <voicing>C F G B D</voicing>\n    </chord>\n  ', 'degrees': ['sub3', 'add4']},
220:{'id': '220', 'name': 'm7b9', 'xml_name': 'minor-seventh', 'voicing': 'C Eb G Bb Db', 'xml_string': b'<chord id="220">\n    <name>m7b9</name>\n    <xml>minor-seventh</xml>\n    <degree>addb9</degree>\n    <voicing>C Eb G Bb Db</voicing>\n    </chord>\n  ', 'degrees': ['addb9']},
221:{'id': '221', 'name': 'm7b13', 'xml_name': 'minor-seventh', 'voicing': 'C Eb G Bb Ab', 'xml_string': b'<chord id="221">\n    <name>m7b13</name>\n    <xml>minor-seventh</xml>\n    <degree>addb13</degree>\n    <voicing>C Eb G Bb Ab</voicing>\n    </chord>\n  ', 'degrees': ['addb13']},
222:{'id': '222', 'name': 'Phryg', 'xml_name': 'minor-seventh', 'voicing': 'C Db Eb F G Bb', 'xml_string': b'<chord id="222">\n    <name>Phryg</name>\n    <xml>minor-seventh</xml>\n    <degree>addb9</degree>\n    <degree>add4</degree>\n    <voicing>C Db Eb F G Bb</voicing>\n    </chord>\n  \n    \n    \n    \n    \n    \n  ', 'degrees': ['addb9', 'add4']},
230:{'id': '230', 'name': '7b9#9', 'xml_name': 'dominant', 'voicing': 'C E G Bb Db D#', 'xml_string': b'<chord id="230">\n    <name>7b9#9</name>\n    <xml>dominant</xml>\n    <degree>addb9</degree>\n    <degree>add#9</degree>\n    <voicing>C E G Bb Db D#</voicing>\n    </chord>\n  ', 'degrees': ['addb9', 'add#9']},
240:{'id': '240', 'name': 'sus#4', 'xml_name': 'major', 'voicing': 'C F# G', 'xml_string': b'<chord id="240">\n    <name>sus#4</name>\n    <xml>major</xml>\n    <degree>sub3</degree>\n    <degree>add#4</degree>\n    <voicing>C F# G</voicing>\n    </chord>\n  ', 'degrees': ['sub3', 'add#4']},
241:{'id': '241', 'name': 'Maj7b13', 'xml_name': 'major-seventh', 'voicing': 'C E G B Ab', 'xml_string': b'<chord id="241">\n    <name>Maj7b13</name>\n    <xml>major-seventh</xml>\n    <degree>addb13</degree>\n    <voicing>C E G B Ab</voicing>\n    </chord>\n  ', 'degrees': ['addb13']},
242:{'id': '242', 'name': '7#9', 'xml_name': 'dominant', 'voicing': 'C E G Bb D#', 'xml_string': b'<chord id="242">\n    <name>7#9</name>\n    <xml>dominant</xml>\n    <voicing>C E G Bb D#</voicing>\n    <degree>add#9</degree>\n    </chord>\n  ', 'degrees': ['add#9']},
243:{'id': '243', 'name': 'm7b5#5', 'xml_name': 'half-diminished', 'voicing': 'C Eb Gb G# Bb', 'xml_string': b'<chord id="243">\n    <name>m7b5#5</name>\n    <xml>half-diminished</xml>\n    <voicing>C Eb Gb G# Bb</voicing>\n    <degree>add#5</degree>\n    </chord>\n  ', 'degrees': ['add#5']},
244:{'id': '244', 'name': 'madd9', 'xml_name': 'minor', 'voicing': 'C Eb G D', 'xml_string': b'<chord id="244">\n    <name>madd9</name>\n    <xml>minor</xml>\n    <voicing>C Eb G D</voicing>\n    <degree>add9</degree>\n    </chord>\n  ', 'degrees': ['add9']},
245:{'id': '245', 'name': '13#9', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb D# A', 'xml_string': b'<chord id="245">\n    <name>13#9</name>\n    <xml>dominant-13th</xml>\n    <voicing>C E G Bb D# A</voicing>\n    <degree>alt#9</degree>\n    </chord>\n  ', 'degrees': ['alt#9']},
246:{'id': '246', 'name': '13b5', 'xml_name': 'dominant-13th', 'voicing': 'C E Gb Bb D A', 'xml_string': b'<chord id="246">\n    <name>13b5</name>\n    <xml>dominant-13th</xml>\n    <voicing>C E Gb Bb D A</voicing>\n    <degree>altb5</degree>    \n    </chord>\n  ', 'degrees': ['altb5']},
247:{'id': '247', 'name': '13b9', 'xml_name': 'dominant-13th', 'voicing': 'C E G Bb Db A', 'xml_string': b'<chord id="247">\n    <name>13b9</name>\n    <xml>dominant-13th</xml>\n    <voicing>C E G Bb Db A</voicing>\n    <degree>altb9</degree>\n    </chord>\n  ', 'degrees': ['altb9']},
248:{'id': '248', 'name': '#11', 'xml_name': 'major', 'voicing': 'C E G F#', 'xml_string': b'<chord id="248">\n    <name>#11</name>\n    <xml>major</xml>\n    <voicing>C E G F#</voicing>\n    <degree>add#11</degree>\n    </chord>\n  ', 'degrees': ['add#11']},
249:{'id': '249', 'name': '+add9', 'xml_name': 'augmented', 'voicing': 'C E G# D', 'xml_string': b'<chord id="249">\n    <name>+add9</name>\n    <xml>augmented</xml>\n    <voicing>C E G# D</voicing>\n    <degree>add9</degree>    \n    </chord>\n  ', 'degrees': ['add9']},
250:{'id': '250', 'name': 'm7b5b13', 'xml_name': 'minor-seventh', 'voicing': 'C Eb Gb Bb D Ab', 'xml_string': b'<chord id="250">\n    <name>m7b5b13</name>\n    <xml>minor-seventh</xml>\n    <voicing>C Eb Gb Bb D Ab</voicing>\n    <degree>altb5</degree>\n    <degree>addb13</degree>\n    </chord>\n  ', 'degrees': ['altb5', 'addb13']},
251:{'id': '251', 'name': 'm6add11', 'xml_name': 'minor-sixth', 'voicing': 'C Eb G A F', 'xml_string': b'<chord id="251">\n    <name>m6add11</name>\n    <xml>minor-sixth</xml>\n    <voicing>C Eb G A F</voicing>\n    <degree>add11</degree>\n    </chord>\n  ', 'degrees': ['add11']},
252:{'id': '252', 'name': '7b5#5', 'xml_name': 'dominant', 'voicing': 'C E Gb G# Bb', 'xml_string': b'<chord id="252">\n    <name>7b5#5</name>\n    <xml>dominant</xml>\n    <voicing>C E Gb G# Bb</voicing>\n    <degree>altb5</degree>\n    <degree>add#5</degree>\n    </chord>\n  ', 'degrees': ['altb5', 'add#5']},
253:{'id': '253', 'name': '11b9', 'xml_name': 'dominant-11th', 'voicing': 'C E G Bb Db F', 'xml_string': b'<chord id="253">\n    <name>11b9</name>\n    <xml>dominant-11th</xml>\n    <voicing>C E G Bb Db F</voicing>\n    <degree>altb9</degree>\n    </chord>\n  ', 'degrees': ['altb9']},
254:{'id': '254', 'name': '13b5b9#11b13', 'xml_name': 'dominant-13th', 'voicing': 'C E Gb Bb Db F# Ab', 'xml_string': b'<chord id="254">\n    <name>13b5b9#11b13</name>\n    <xml>dominant-13th</xml>\n    <degree>altb5</degree>\n    <degree>altb9</degree>\n    <degree>alt#11</degree>\n    <degree>altb13</degree>\n    <voicing>C E Gb Bb Db F# Ab</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'altb9', 'alt#11', 'altb13']},
255:{'id': '255', 'name': '13b5b9#11', 'xml_name': 'dominant-13th', 'voicing': 'C E Gb Bb Db F# A', 'xml_string': b'<chord id="255">\n    <name>13b5b9#11</name>\n    <xml>dominant-13th</xml>\n    <degree>altb5</degree>\n    <degree>altb9</degree>\n    <degree>alt#11</degree>\n    <voicing>C E Gb Bb Db F# A</voicing>\n    </chord>\n  ', 'degrees': ['altb5', 'altb9', 'alt#11']},
256:{'id': '256', 'name': 'm7M7', 'xml_name': 'minor-seventh', 'voicing': 'C Eb G Bb B', 'xml_string': b'<chord id="256">\n    <name>m7M7</name>\n    <xml>minor-seventh</xml>\n    <voicing>C Eb G Bb B</voicing>\n    <degree>add7</degree>\n    </chord>\n  ', 'degrees': ['add7']},
257:{'id': '257', 'name': '7#9#11', 'xml_name': 'dominant', 'voicing': 'C E G Bb D# F#', 'xml_string': b'<chord id="257">\n    <name>7#9#11</name>\n    <xml>dominant</xml>\n    <degree>add#9</degree>\n    <degree>add#11</degree>\n    <voicing>C E G Bb D# F#</voicing>\n    </chord>\n  ', 'degrees': ['add#9', 'add#11']},
258:{'id': '258', 'name': '6add#9', 'xml_name': 'major-sixth', 'voicing': 'C E G A D#', 'xml_string': b'<chord id="258">\n    <name>6add#9</name>\n    <xml>major-sixth</xml>\n    <degree>add#9</degree>\n    <voicing>C E G A D#</voicing>\n    </chord>\n ', 'degrees': ['add#9']},
259:{'id': '259', 'name': 'sus24', 'xml_name': 'suspended-second-fourth', 'voicing': 'C D F', 'xml_string': b'<chord id="259">\n    <name>sus24</name>\n    <xml>suspended-second-fourth</xml>\n    <voicing>C D F</voicing>\n    </chord>\n ', 'degrees': []},
260:{'id': '260', 'name': '6add9sub3', 'xml_name': 'major-sixth', 'voicing': 'C G A D', 'xml_string': b'<chord id="260">\n    <name>6add9sub3</name>\n    <xml>major-sixth</xml>\n    <degree>add9</degree>\n    <degree>sub3</degree>\n    <voicing>C G A D</voicing>\n    </chord>\n  ', 'degrees': ['add9', 'sub3']},
261:{'id': '261', 'name': 'sus4add9', 'xml_name': 'suspended-fourth', 'voicing': 'C F G D', 'xml_string': b'<chord id="261">\n    <name>sus4add9</name>\n    <xml>suspended-fourth</xml>\n    <voicing>C F G D</voicing>\n    <degree>add9</degree>\n    </chord>\n  ', 'degrees': ['add9']},
262:{'id': '262', 'name': 'm9add13', 'xml_name': 'minor-ninth', 'voicing': 'C Eb G Bb D A', 'xml_string': b'<chord id="262">\n    <name>m9add13</name>\n    <xml>minor-ninth</xml>\n    <voicing>C Eb G Bb D A</voicing>\n    <degree>add13</degree>\n    </chord>\n  ', 'degrees': ['add13']},
263:{'id': '263', 'name': 'add9b5', 'xml_name': 'major', 'voicing': 'C E Gb D', 'xml_string': b'<chord id="263">\n    <name>add9b5</name>\n    <xml>major</xml>\n    <degree>add9</degree>\n    <degree>altb5</degree>\n    <voicing>C E Gb D</voicing>\n    </chord>\n  ', 'degrees': ['add9', 'altb5']},
264:{'id': '264', 'name': 'dim7M7', 'xml_name': 'diminished', 'voicing': 'C Eb Gb A B', 'xml_string': b'<chord id="264">\n    <name>dim7M7</name>\n    <xml>diminished</xml>\n    <degree>add#7</degree>\n    <degree>add6</degree>\n      <voicing>C Eb Gb A B</voicing>\n    </chord>\n  ', 'degrees': ['add#7', 'add6']},
265:{'id': '265', 'name': 'm7add11', 'xml_name': 'minor-seventh', 'voicing': 'C Eb G Bb F', 'xml_string': b'<chord id="265">\n    <name>m7add11</name>\n    <xml>minor-seventh</xml>\n    <voicing>C Eb G Bb F</voicing>\n    <degree>add11</degree>\n    </chord>\n  ', 'degrees': ['add11']},
266:{'id': '266', 'name': '6add9#11', 'xml_name': 'major-sixth', 'voicing': 'C E G A D F#', 'xml_string': b'<chord id="266">\n    <name>6add9#11</name>\n    <xml>major-sixth</xml>\n    <degree>add9</degree>\n    <degree>add#11</degree>\n    <voicing>C E G A D F#</voicing>\n    </chord>\n  ', 'degrees': ['add9', 'add#11']},
267:{'id': '267', 'name': '7#9sus', 'xml_name': 'suspended-fourth', 'voicing': 'C F G Bb D#', 'xml_string': b'<chord id="267">\n    <name>7#9sus</name>\n    <xml>suspended-fourth</xml>\n    <degree>add7</degree>\n    <degree>add#9</degree>\n    <voicing>C F G Bb D#</voicing>\n    </chord>\n  ', 'degrees': ['add7', 'add#9']},
185:{'id': '185', 'name': 'dim7add9', 'xml_name': 'diminished-seventh', 'voicing': 'C Eb Gb A D', 'xml_string': b'<chord id="185">\n    <name>dim7add9</name>\n    <xml>diminished-seventh</xml>\n    <voicing>C Eb Gb A D</voicing>\n    <degree>add9</degree>\n    </chord>\n  ', 'degrees': ['add9']},
}

voicing_to_chord_id = {
'C E G':1,
'C E Gb':3,
'C E G#':4,
'C E G A':5,
'C E G B':6,
'C E G B D':7,
'C E G B D F#':8,
'C E G B D F# A':9,
'C G B D':11,
'C E G# B':13,
'C E G A D':14,
'C Eb G':16,
'C Eb G B':18,
'C Eb G Bb':19,
'C Eb G Bb D':20,
'C Eb G Bb D F':21,
'C Eb G Bb D F A':22,
'C Eb G A':23,
'C Eb G#':24,
'C Eb G# Bb':25,
'C Eb G A D':26,
'C E Gb B':29,
'C Eb Gb Bb':32,
'C Eb Gb':33,
'C Eb Gb Bb D':34,
'C G':40,
'C E Ab':56,
'C E Ab Bb D':57,
'C E G Bb':64,
'C E G Bb D F A':65,
'C E G Ab Bb':66,
'C E G Bb F#':67,
'C E G Bb D F# A':68,
'C E G Bb F# Ab':69,
'C E G Bb D':70,
'C E G Bb D Ab':72,
'C E G Bb D F#':73,
'C E G Bb D F# Ab':75,
'C E G Bb Db':76,
'C E G Bb Db F A':77,
'C E G Bb Db Ab':78,
'C E G Bb Db F#':79,
'C E G Bb Db F# A':80,
'C E G Bb Db F# Ab':81,
'C E G Bb Eb':82,
'C E G Bb D# F A':83,
'C E G Bb D# Ab':84,
'C E G Bb D# F# A':86,
'C E G Bb D# F# Ab':87,
'C E Gb Bb':88,
'C E Gb Bb D F A':89,
'C E Gb Bb A':90,
'C E Gb Bb D':91,
'C E Gb Bb D Ab':92,
'C E Gb Bb Db':93,
'C E Gb Bb Db F A':94,
'C E Gb Bb Db Ab':95,
'C E Gb Bb D#':96,
'C E Gb Bb D# F A':97,
'C E Gb Bb D# Ab':98,
'C E Ab Bb':99,
'C E G# Bb D F A':100,
'C E G# Bb F#':101,
'C E G# Bb D':103,
'C E G# Bb D F#':104,
'C E G# Bb Db':105,
'C E G# Bb Db F A':106,
'C E G# Bb Db F#':107,
'C E G# Bb Db F# A':108,
'C E G# Bb D#':109,
'C E G# Bb D# F# A':110,
'C E G# Bb D# F#':111,
'C E G# Bb':113,
'C F G Bb':128,
'C F G Bb D A':129,
'C F G Bb Ab':130,
'C F G Bb F':131,
'C F G Bb F# Ab':133,
'C F G Bb D':134,
'C F G Bb D Ab':135,
'C F G Bb D F#':136,
'C F G Bb D F# A':137,
'C F G Bb D F# Ab':139,
'C F G Bb Db':140,
'C F G Bb Db F A':141,
'C F G Bb Db Ab':142,
'C F G Bb Db F#':143,
'C F G Bb Dd F# A':144,
'C F G Bb Db F# Ab':145,
'C F G Bb Eb':146,
'C F G Bb D# A':147,
'C F G Bb D# Ab':148,
'C F G Bb D# F# A':150,
'C F G Bb D# F# Ab':151,
'C F Gb Bb':152,
'C F Gb Bb D A':153,
'C F Gb Bb Ab':154,
'C F Gb Bb D':155,
'C F Gb Bb D Ab':156,
'C F Gb Bb Db':157,
'C F Gb Bb Db Ab':159,
'C F Gb Bb Eb':160,
'C F Gb Bb D# A':161,
'C F Gb Bb Eb Ab':162,
'C F Ab Bb':163,
'C F G# Bb D A':164,
'C F G# Bb F#':165,
'C F G# Bb D F# A':166,
'C F G# Bb D':167,
'C F G# Bb D F#':168,
'C F Ab Bb Db':169,
'C F G# Bb Db A':170,
'C F Ab Bb Db Gb':171,
'C F G# Bb Db F# A':172,
'C F Ab Bb Eb':173,
'C F G# Bb D# F# A':174,
'C F Ab Bb Eb Gb':175,
'C E F G':177,
'C F G':184,
'C Eb Gb Bbb':185,
'C D G':186,
'C Eb Ab':187,
'C E G A#':188,
'C E G F# A#':189,
'C E G A D':191,
'C E G Bb D F':193,
'C E G B D F':194,
'C F# A# D':195,
'C Eb F G Bb':196,
'C E G A B':197,
'C D Eb G':198,
'C Eb G B D':199,
'C Eb Gb Bb D F':201,
'C Eb Gb B':202,
'C E Ab D':203,
'C E':204,
'C E G# Bb D A':207,
'C E G B F#':210,
'C E G# B D':211,
'C E G B D#':212,
'C D E G':213,
'C E G D':214,
'C Db F G':215,
'C F G B':216,
'C F G B D':217,
'C Eb G Bb Db':220,
'C Eb G Bb Ab':221,
'C Db Eb F G Bb':222,
'C E G Bb Db D#':230,
'C F# G':240,
'C E G B Ab':241,
'C E G Bb D#':242,
'C Eb Gb G# Bb':243,
'C Eb G D':244,
'C E G Bb D# A':245,
'C E Gb Bb D A':246,
'C E G Bb Db A':247,
'C E G F#':248,
'C E G# D':249,
'C Eb Gb Bb D Ab':250,
'C Eb G A F':251,
'C E Gb G# Bb':252,
'C E G Bb Db F':253,
'C E Gb Bb Db F# Ab':254,
'C E Gb Bb Db F# A':255,
'C Eb G Bb B':256,
'C E G Bb D# F#':257,
'C E G A D#':258,
'C D F':259,
'C G A D':260,
'C F G D':261,
'C Eb G Bb D A':262,
'C E Gb D':263,
'C Eb Gb A B':264,
'C Eb G Bb F':265,
'C E G A D F#':266,
'C F G Bb D#':267,
'C Eb Gb A D':185,
}

chord_name_to_chord_id = {
'':1,
'5b':3,
'+':4,
'6':5,
'Maj7':6,
'Maj9':7,
'Maj9#11':8,
'Maj13#11':9,
'Maj9(no 3)':11,
'Maj7#5':13,
'6add9':14,
'm':16,
'mMaj7':18,
'm7':19,
'm9':20,
'm11':21,
'm13':22,
'm6':23,
'm#5':24,
'm7#5':25,
'm6add9':26,
'Maj7b5':29,
'm7b5':32,
'dim':33,
'm9b5':34,
'5':40,
'7+':56,
'9+':57,
'7':64,
'13':65,
'7b13':66,
'7#11':67,
'13#11':68,
'7#11b13':69,
'9':70,
'9b13':72,
'9#11':73,
'9#11b13':75,
'7b9':76,
'13b9':77,
'7b9b13':78,
'7b9#11':79,
'13b9#11':80,
'7b9#11b13':81,
'7#9':82,
'13#9':83,
'7#9b13':84,
'13#9#11':86,
'7#9#11b13':87,
'7b5':88,
'13b5':89,
'7b5b13':90,
'9b5':91,
'9b5b13':92,
'7b5b9':93,
'13b5b9':94,
'7b5b9b13':95,
'7b5#9':96,
'13b5#9':97,
'7b5#9b13':98,
'7#5':99,
'13#5':100,
'7#5#11':101,
'9#5':103,
'9#5#11':104,
'7#5b9':105,
'13#5b9':106,
'7#5b9#11':107,
'13#5b9#11':108,
'7#5#9':109,
'13#5#9#11':110,
'7#5#9#11':111,
'7#5':113,
'7sus':128,
'13sus':129,
'7susb13':130,
'7sus#11':131,
'7sus#11b13':133,
'9sus':134,
'9susb13':135,
'9sus#11':136,
'13sus#11':137,
'9sus#11b13':139,
'7susb9':140,
'13susb9':141,
'7susb9b13':142,
'7susb9#11':143,
'13susb9#11':144,
'7susb9#11b13':145,
'7sus#9':146,
'13sus#9':147,
'7sus#9b13':148,
'13sus#9#11':150,
'7sus#9#11b13':151,
'7susb5':152,
'13susb5':153,
'7susb5b13':154,
'9susb5':155,
'9susb5b13':156,
'7susb5b9':157,
'7susb5b9b13':159,
'7susb5#9':160,
'13susb5#9':161,
'7susb5#9b13':162,
'7sus#5':163,
'13sus#5':164,
'7sus#5#11':165,
'13sus#5#11':166,
'9sus#5':167,
'9sus#5#11':168,
'7sus#5b9':169,
'13sus#5b9':170,
'7sus#5b9#11':171,
'13sus#5b9#11':172,
'7sus#5#9':173,
'13sus#5#9#11':174,
'7sus#5#9#11':175,
'add4':177,
'sus':184,
'dim7':185,
'sus2':186,
'maddb13':187,
'add#13':188,
'add#11#13':189,
'6add9':191,
'11':193,
'Maj11':194,
'Tristan':195,
'm7add11':196,
'Maj7add13':197,
'madd9':198,
'm9Maj7':199,
'm11b5':201,
'dimMaj7':202,
'aug9':203,
'omit5':204,
'aug13':207,
'Maj7#11':210,
'Maj9#5':211,
'Maj7#9':212,
'add2':213,
'add9':214,
'susb9':215,
'Maj7sus':216,
'Maj9sus':217,
'm7b9':220,
'm7b13':221,
'Phryg':222,
'7b9#9':230,
'sus#4':240,
'Maj7b13':241,
'7#9':242,
'm7b5#5':243,
'madd9':244,
'13#9':245,
'13b5':246,
'13b9':247,
'#11':248,
'+add9':249,
'm7b5b13':250,
'm6add11':251,
'7b5#5':252,
'11b9':253,
'13b5b9#11b13':254,
'13b5b9#11':255,
'm7M7':256,
'7#9#11':257,
'6add#9':258,
'sus24':259,
'6add9sub3':260,
'sus4add9':261,
'm9add13':262,
'add9b5':263,
'dim7M7':264,
'm7add11':265,
'6add9#11':266,
'7#9sus':267,
'dim7add9':185,
}